name = "Craft to Exile 2: Eartharia Edition"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f147901dfb3b92677a8effde028d5fdb61b1517edf2344141f542538283b0b53"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
