name = "Craft to Exile 2: Eartharia Edition"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e570466b2fc9c1edf9beba1fd4f2408e295a7b24b47464cfe2f08c66a8461851"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
