name = "Craft to Exile 2: Eartharia Edition"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7826cb7b02cedec83e21a1da80163f7b18b45a476245378282b16d4d163e2b2c"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
