name = "Craft to Exile 2: Eartharia Edition"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6528acb00bec8f235f645ec8ab18c0f03004938539318f737193ca8363322c27"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
