name = "Craft to Exile 2: Eartharia Edition"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e26a54dd81739d63506a0db2a350c4d769dc1193fc8f8a133c562a4b5d65570"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
